"""documents, extractions, ai usage

Revision ID: 0601219aa7ac
Revises: 0a24c5aa99d9
Create Date: 2026-07-29 00:55:39.741250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0601219aa7ac'
down_revision: Union[str, Sequence[str], None] = '0a24c5aa99d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cache_hit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('succeeded', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index('ix_ai_usage_claim_id', 'ai_usage', ['claim_id'], unique=False, schema='ai')
    op.create_index('ix_ai_usage_created_at', 'ai_usage', ['created_at'], unique=False, schema='ai')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), server_default='unknown', nullable=False),
    sa.Column('processing_status', sa.String(length=32), server_default='uploaded', nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('police_report', 'invoice', 'medical_bill', 'repair_estimate', 'photo', 'other', 'unknown')", name='ck_documents_doc_type'),
    sa.CheckConstraint("processing_status IN ('uploaded', 'extracting', 'extracted', 'failed')", name='ck_documents_processing_status'),
    sa.CheckConstraint('size_bytes > 0', name='ck_documents_size_bytes'),
    sa.PrimaryKeyConstraint('id'),
    schema='documents'
    )
    op.create_index('ix_documents_claim_id', 'documents', ['claim_id'], unique=False, schema='documents')
    op.create_index('ix_documents_content_hash', 'documents', ['content_hash'], unique=False, schema='documents')
    op.create_table('extractions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('succeeded', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='documents'
    )
    op.create_index('ix_extractions_document_id', 'extractions', ['document_id'], unique=False, schema='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extractions_document_id', table_name='extractions', schema='documents')
    op.drop_table('extractions', schema='documents')
    op.drop_index('ix_documents_content_hash', table_name='documents', schema='documents')
    op.drop_index('ix_documents_claim_id', table_name='documents', schema='documents')
    op.drop_table('documents', schema='documents')
    op.drop_index('ix_ai_usage_created_at', table_name='ai_usage', schema='ai')
    op.drop_index('ix_ai_usage_claim_id', table_name='ai_usage', schema='ai')
    op.drop_table('ai_usage', schema='ai')
    # ### end Alembic commands ###
