"""vector collections and embedding cache

Revision ID: 27076aeb634f
Revises: 0601219aa7ac
Create Date: 2026-07-29 02:46:37.814737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '27076aeb634f'
down_revision: Union[str, Sequence[str], None] = '0601219aa7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_precedents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('claim_reference', sa.String(length=32), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('loss_type', sa.String(length=32), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fraud_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_band IN ('low', 'medium', 'high')", name='ck_precedents_risk_band'),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index('ix_claim_precedents_content_hash', 'claim_precedents', ['content_hash'], unique=False, schema='ai')
    op.create_table('embedding_cache',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('content_hash', 'model'),
    schema='ai'
    )
    op.create_table('policy_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_table('policy_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('policy_document_id', sa.UUID(), nullable=False),
    sa.Column('section_ref', sa.String(length=64), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_exclusion', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ordinal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_document_id'], ['ai.policy_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index('ix_policy_chunks_content_hash', 'policy_chunks', ['content_hash'], unique=False, schema='ai')
    op.create_index('ix_policy_chunks_document_id', 'policy_chunks', ['policy_document_id'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_policy_chunks_document_id', table_name='policy_chunks', schema='ai')
    op.drop_index('ix_policy_chunks_content_hash', table_name='policy_chunks', schema='ai')
    op.drop_table('policy_chunks', schema='ai')
    op.drop_table('policy_documents', schema='ai')
    op.drop_table('embedding_cache', schema='ai')
    op.drop_index('ix_claim_precedents_content_hash', table_name='claim_precedents', schema='ai')
    op.drop_table('claim_precedents', schema='ai')
    # ### end Alembic commands ###
