"""users table

Revision ID: 33c4d2d711e1
Revises: 4251083376c8
Create Date: 2026-07-28 13:12:37.694902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c4d2d711e1'
down_revision: Union[str, Sequence[str], None] = '4251083376c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('authority_limit', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('adjuster', 'senior_adjuster', 'admin')", name='ck_users_role'),
    sa.CheckConstraint('authority_limit >= 0', name='ck_users_authority_limit_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    schema='claims'
    )
    op.create_index(op.f('ix_claims_users_email'), 'users', ['email'], unique=True, schema='claims')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_users_email'), table_name='users', schema='claims')
    op.drop_table('users', schema='claims')
    # ### end Alembic commands ###
