"""assessments and citations

Revision ID: 738632103227
Revises: 12f5d4123e21
Create Date: 2026-07-29 04:29:35.521279

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "738632103227"
down_revision: str | Sequence[str] | None = "12f5d4123e21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("coverage_verdict", sa.String(length=32), nullable=False),
        sa.Column("coverage_rationale", sa.Text(), nullable=False),
        sa.Column("risk_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("risk_band", sa.String(length=16), nullable=False),
        sa.Column("risk_rationale", sa.Text(), nullable=False),
        sa.Column("recommended_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "coverage_verdict IN ('covered', 'partially_covered', 'not_covered', 'indeterminate')",
            name="ck_assessments_verdict",
        ),
        sa.CheckConstraint(
            "risk_band IN ('low', 'medium', 'high')", name="ck_assessments_risk_band"
        ),
        sa.CheckConstraint(
            "risk_score >= 0 AND risk_score <= 100", name="ck_assessments_risk_score"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="ai",
    )
    op.create_index(
        "ix_assessments_claim_id", "assessments", ["claim_id"], unique=False, schema="ai"
    )
    op.create_index(
        "ix_assessments_created_at", "assessments", ["created_at"], unique=False, schema="ai"
    )
    op.create_table(
        "assessment_citations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_ref", sa.String(length=128), nullable=False),
        sa.Column("relevance", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("quoted_span", sa.Text(), nullable=True),
        sa.Column("supports", sa.String(length=32), server_default="coverage", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_type IN ('policy_chunk', 'precedent')", name="ck_citations_source_type"
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["ai.assessments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="ai",
    )
    op.create_index(
        "ix_assessment_citations_assessment_id",
        "assessment_citations",
        ["assessment_id"],
        unique=False,
        schema="ai",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_assessment_citations_assessment_id", table_name="assessment_citations", schema="ai"
    )
    op.drop_table("assessment_citations", schema="ai")
    op.drop_index("ix_assessments_created_at", table_name="assessments", schema="ai")
    op.drop_index("ix_assessments_claim_id", table_name="assessments", schema="ai")
    op.drop_table("assessments", schema="ai")
    # ### end Alembic commands ###
