"""policies, claims, claim status history

Revision ID: b19572c9d097
Revises: 33c4d2d711e1
Create Date: 2026-07-28 13:59:54.411631

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b19572c9d097"
down_revision: str | Sequence[str] | None = "33c4d2d711e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("policy_number", sa.String(length=32), nullable=False),
        sa.Column("policyholder_name", sa.String(length=200), nullable=False),
        sa.Column("product_type", sa.String(length=32), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=False),
        sa.Column("coverage_limit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "deductible", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "product_type IN ('motor', 'property', 'liability', 'marine')",
            name="ck_policies_product_type",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'lapsed', 'cancelled')", name="ck_policies_status"
        ),
        sa.CheckConstraint("coverage_limit > 0", name="ck_policies_coverage_limit"),
        sa.CheckConstraint("deductible >= 0", name="ck_policies_deductible"),
        sa.CheckConstraint("effective_to > effective_from", name="ck_policies_period"),
        sa.PrimaryKeyConstraint("id"),
        schema="claims",
    )
    op.create_index(
        op.f("ix_claims_policies_policy_number"),
        "policies",
        ["policy_number"],
        unique=True,
        schema="claims",
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("claim_number", sa.String(length=32), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("assigned_adjuster_id", sa.UUID(), nullable=True),
        sa.Column("loss_date", sa.Date(), nullable=False),
        sa.Column(
            "reported_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("loss_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("claimed_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="submitted", nullable=False),
        sa.Column("settled_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("risk_band", sa.String(length=16), nullable=True),
        sa.Column("latest_assessment_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "loss_type IN ('collision', 'theft', 'fire', 'flood', 'storm', 'liability', 'other')",
            name="ck_claims_loss_type",
        ),
        sa.CheckConstraint(
            "risk_band IS NULL OR risk_band IN ('low', 'medium', 'high')",
            name="ck_claims_risk_band",
        ),
        sa.CheckConstraint(
            "status IN ('submitted', 'triaged', 'under_review', 'pending_approval', 'approved', 'settled', 'denied', 'withdrawn')",
            name="ck_claims_status",
        ),
        sa.CheckConstraint("claimed_amount > 0", name="ck_claims_claimed_amount"),
        sa.CheckConstraint(
            "settled_amount IS NULL OR settled_amount >= 0", name="ck_claims_settled_amount"
        ),
        sa.ForeignKeyConstraint(
            ["assigned_adjuster_id"],
            ["claims.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["claims.policies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="claims",
    )
    op.create_index(
        "ix_claims_assigned_adjuster_id",
        "claims",
        ["assigned_adjuster_id"],
        unique=False,
        schema="claims",
    )
    op.create_index(
        op.f("ix_claims_claims_claim_number"),
        "claims",
        ["claim_number"],
        unique=True,
        schema="claims",
    )
    op.create_index("ix_claims_policy_id", "claims", ["policy_id"], unique=False, schema="claims")
    op.create_index("ix_claims_status", "claims", ["status"], unique=False, schema="claims")
    op.create_table(
        "claim_status_history",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(actor_type = 'system' AND actor_id IS NULL) OR (actor_type = 'user' AND actor_id IS NOT NULL)",
            name="ck_history_actor_consistency",
        ),
        sa.CheckConstraint("actor_type IN ('user', 'system')", name="ck_history_actor_type"),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["claims.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.claims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="claims",
    )
    op.create_index(
        "ix_claim_status_history_claim_id",
        "claim_status_history",
        ["claim_id"],
        unique=False,
        schema="claims",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_claim_status_history_claim_id", table_name="claim_status_history", schema="claims"
    )
    op.drop_table("claim_status_history", schema="claims")
    op.drop_index("ix_claims_status", table_name="claims", schema="claims")
    op.drop_index("ix_claims_policy_id", table_name="claims", schema="claims")
    op.drop_index(op.f("ix_claims_claims_claim_number"), table_name="claims", schema="claims")
    op.drop_index("ix_claims_assigned_adjuster_id", table_name="claims", schema="claims")
    op.drop_table("claims", schema="claims")
    op.drop_index(op.f("ix_claims_policies_policy_number"), table_name="policies", schema="claims")
    op.drop_table("policies", schema="claims")
    # ### end Alembic commands ###
